<!DOCTYPE html>
<html>
	<meta charset="utf-8">
	<title>Test Suite</title>
	<link rel="stylesheet" href="qunit-2.15.0.css">
	<script type="module">
		import {evaluateTestSuite} from './lit.js'

		QUnit.module('core', function() {
			QUnit.module('evaluate a single test', function() {
				QUnit.test(
				'transforms correct assertion to successful test result', 
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => ({check: 2, equals: 2})
					})

					assert.deepEqual(actual, {'': {kind: 'pass'}})
				})

				QUnit.test(
				'transforms incorrect assertion to failure test result',
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => ({check: 2 + 2, equals: 5})
					})

					const expected = {
						'': {
							kind: 'fail', 
							reason: {
								kind: 'not-equal',
								actual: 4,
								expected: 5
							}
						}
					}
					
					assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'handles non-primitive equality with deep equals',
				async function (assert) {
					const actual = await evaluateTestSuite({
						'': () => ({
							check: {x: 2, y: {z: 4}},
							deepEquals: {x: 2, y: {z: 4}}
						})
					})
					assert.deepEqual(actual, {'': {kind: 'pass'}})
				})

				QUnit.test(
				'can ensure a test throws the right exception',
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => ({
							check: () => { throw {failure: 'to communicate' } },
							throws: {failure: 'to communicate'}
						})
					})
					
					assert.deepEqual(actual, {'': {kind: 'pass'}})
				})

				QUnit.test(
				"responds intelligently when the expected exception doesn't happen",
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => ({
							check: () => {},
							throws: {iAmComputer: 'feed me data'}
						})
					})

					const expected = {
						'': {
							kind: 'fail',
							reason: {
								kind: 'not-equal',
								actual: undefined,
								expected: {iAmComputer: 'feed me data'}
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'fails when the wrong error is thrown', 
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => ({
							check: () => { throw 'actual' },
							throws: 'expected'
						})
					})

					const expected = {
						'': {
							kind: 'fail',
							reason: {
								kind: 'not-equal',
								actual: 'actual', 
								expected: 'expected'
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})
				
				QUnit.test(
				'gracefully deals with an unexpected error',
				async function(assert) {
					const actual = await evaluateTestSuite({
						'': () => {
							throw 'whoops'
						}
					})

					const expected = {
						'': {
							kind: 'fail',
							reason: {
								kind: 'threw-exn',
								error: 'whoops'
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})
			})
			
			QUnit.module("evaluate test suites", function() {
				QUnit.test(
				"handles empty suite",
				async function(assert) {
					const actual = await evaluateTestSuite({})
					return assert.deepEqual(actual, {})
				})

				QUnit.test(
				"Preserves the structure of unbalanced trees",
				async function(assert) {
					const actual = await evaluateTestSuite({
						'two plus two': () => ({
							check: 2 + 2,
							equals: 5
						}),
						'functions gone wild': {
							'naughty': () => ({
								check: () => { throw 'error' },
								throws: 'error'
							}),
							'nice': () => ({
								check: () => {},
								throws: 'error'
							})
						}
					})

					const expected = {
						'two plus two': {
							kind: 'fail',
							reason: {
								kind: 'not-equal',
								actual: 4,
								expected: 5
							}
						},
						'functions gone wild': {
							'naughty': {kind: 'pass'},
							'nice': {
								kind: 'fail', 
								reason: {
									kind: 'not-equal',
									actual: undefined, 
									expected: 'error'
								}
							}
						}
					}
					
					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'Resolves asynchronous tests',
				async function(assert) {
					const actual = await evaluateTestSuite({
						'myAsyncFunction': () => Promise.resolve({check: 1, equals: 1})
					})

					const expected = {'myAsyncFunction': {kind: 'pass'}}

					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'meta-test 1',
				async function(assert) {
					const actual = await evaluateTestSuite({
						'core': {
							'evaluate a single test': {
								'transforms correct assertion to successful test result': async () => ({ 
										check: await evaluateTestSuite({
										'': () => ({check: 2, equals: 2})
										}),
										deepEquals: {'': {kind: 'pass'}}
								})
							}
						}
					})

					const expected = {
						'core': {
							'evaluate a single test': {
								'transforms correct assertion to successful test result': {
									kind: 'pass'
								}
							}
						}
					}

					return assert.deepEqual(actual, expected)						
				})
			})
		})
	</script>
	<body>
		<div id="qunit"></div>
		<div id="qunit-fixture"></div>
		<script src="qunit-2.15.0.js"></script>
	</body>
</html>
