<!DOCTYPE html>
<html>
	<meta charset="utf-8">
	<title>Test Suite</title>
	<link rel="stylesheet" href="qunit-2.15.0.css">
	<script type="module">
		import {evalTestSuite} from './lit.js'

		QUnit.module('core', function() {
			QUnit.module('eval a single test', function() {
				QUnit.test(
				'transforms correct assertion to successful test result', 
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => ({check: 2, equals: 2})
					})

					const expected = {
						passes: 1,
						fails: 0,
						children: {
							'': {kind: 'pass'}
						}
					}

					assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'transforms incorrect assertion to failure test result',
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => ({check: 2 + 2, equals: 5})
					})

					const expected = {
						passes: 0,
						fails: 1,
						children: {
							'': {
								kind: 'fail', 
								reason: {
									kind: 'not-equal',
									actual: 4,
									expected: 5
								}
							}
						}
					}
					
					assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'handles non-primitive equality with deep equals',
				async function (assert) {
					const actual = await evalTestSuite({
						'': () => ({
							check: {x: 2, y: {z: 4}},
							deepEquals: {x: 2, y: {z: 4}}
						})
					})

					const expected = {
						passes: 1,
						fails: 0,
						children: {
							'': {kind: 'pass'}
						}
					}

					assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'can ensure a test throws the right exception',
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => ({
							check: () => { throw {failure: 'to communicate' } },
							throws: {failure: 'to communicate'}
						})
					})

					const expected =  {
						passes: 1,
						fails: 0,
						children: {
							'': {kind: 'pass'}
						}
					}
					
					assert.deepEqual(actual, expected)
				})

				QUnit.test(
				"responds intelligently when the expected exception doesn't happen",
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => ({
							check: () => {},
							throws: {iAmComputer: 'feed me data'}
						})
					})

					const expected = {
						passes: 0,
						fails: 1,
						children: {
							'': {
								kind: 'fail',
								reason: {
									kind: 'not-equal',
									actual: undefined,
									expected: {iAmComputer: 'feed me data'}
								}
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'fails when the wrong error is thrown', 
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => ({
							check: () => { throw 'actual' },
							throws: 'expected'
						})
					})

					const expected = {
						passes: 0,
						fails: 1,
						children: {
							'': {
								kind: 'fail',
								reason: {
									kind: 'not-equal',
									actual: 'actual', 
									expected: 'expected'
								}
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})
				
				QUnit.test(
				'gracefully deals with an unexpected error',
				async function(assert) {
					const actual = await evalTestSuite({
						'': () => {
							throw 'whoops'
						}
					})

					const expected = {
						passes: 0,
						fails: 1,
						children: {
							'': {
								kind: 'fail',
								reason: {
									kind: 'threw-exn',
									error: 'whoops'
								}
							}
						}
					}

					return assert.deepEqual(actual, expected)
				})
			})
			
			QUnit.module("eval test suites", function() {
				QUnit.test(
				"handles empty suite",
				async function(assert) {
					const actual = await evalTestSuite({})
					const expected = {passes: 0, fails: 0, children: {}}
					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				"Preserves the structure of unbalanced trees",
				async function(assert) {
					const actual = await evalTestSuite({
						'two plus two': () => ({
							check: 2 + 2,
							equals: 5
						}),
						'functions gone wild': {
							'naughty': () => ({
								check: () => { throw 'error' },
								throws: 'error'
							}),
							'nice': () => ({
								check: () => {},
								throws: 'error'
							})
						}
					})

					const expected = {
						passes: 1,
						fails: 2,
						children: {
							'two plus two': {
								kind: 'fail',
								reason: {
									kind: 'not-equal',
									actual: 4,
									expected: 5
								}
							},
							'functions gone wild': {
								passes: 1,
								fails: 1,
								children: {
									'naughty': {kind: 'pass'},
									'nice': {
										kind: 'fail', 
										reason: {
											kind: 'not-equal',
											actual: undefined, 
											expected: 'error'
										}
									}
								}
							}
						}
					}
					
					return assert.deepEqual(actual, expected)
				})

				QUnit.test(
				'Resolves asynchronous tests',
				async function(assert) {
					const actual = await evalTestSuite({
						'myAsyncFunction': () => Promise.resolve({check: 1, equals: 1})
					})
					
					const expected = {
						passes: 1,
						fails: 0,
						children: {
							'myAsyncFunction': {kind: 'pass'}
						}
					}

					return assert.deepEqual(actual, expected)
				})
			})
		})
	</script>
	<body>
		<div id="qunit"></div>
		<div id="qunit-fixture"></div>
		<script src="qunit-2.15.0.js"></script>
	</body>
</html>
